### ISSUE TITLE
Login.css

### ISSUE THREAD

**Issue by 04Jatin** [47JATIN/SCM-PROJECT-FINAL#13]
Expected Behavior:

The login form should be centered on the page.
The input fields should have appropriate padding and margins.
The submit button should be properly aligned and styled.
Actual Behavior:

The login form is misaligned and appears off-center.
Input fields are lacking adequate padding and margins, making them look cramped.
The submit button is not aligned correctly and its style does not match the design guidelines.

**Comment by 47JATIN** [comment]
done by jatin gupta
